### ISSUE TITLE
[css-view-transitions-1] finished promise timing

### ISSUE THREAD

**Issue by vmpstr** [w3c/csswg-drafts#12442]
In [css-view-transitions-1's Handle Transition Frame](https://www.w3.org/TR/css-view-transitions-1/#handle-transition-frame-algorithm), step 4 says

> 1. Set transition’s [phase](https://www.w3.org/TR/css-view-transitions-1/#viewtransition-phase) to "done".
> 2. [Clear view transition](https://www.w3.org/TR/css-view-transitions-1/#clear-view-transition) transition.
> 3. [Resolve](https://webidl.spec.whatwg.org/#resolve) transition’s [finished promise](https://www.w3.org/TR/css-view-transitions-1/#viewtransition-finished-promise).
> 4. Return.

Since we resolve the promise in 3, the earliest opportunity for script to run is at the next microtask checkpoint. However, these steps are executed via [perform pending transition operations](https://www.w3.org/TR/css-view-transitions-1/#ref-for-handle-transition-frame) which is invoked in the [Update the Rendering loop](https://html.spec.whatwg.org/#event-loop-processing-model:perform-pending-transition-operations), which doesn't have a microtask checkpoint before producing a visual frame.

This means that we are guaranteed to present one visual frame _after_ view transition is ended but _before_ script had a chance to run.

In some situations, this causes a flicker if we're transferring some style from the group pseudo to the final destination element. Here's an example where the box shadow is applied to the group pseudo and transferred to the final element when the transition finishes: https://vmpstr.github.io/htmldemos/vt/flicker.html (you might have to click a few times, but the flicker is definitely there in both Chrome and Safari). The workaround toggle listens to the first Animation object's finish promise (which resolves and runs outside of the rendering loop) to do the same work, and the flicker disappears.

My proposal to avoid this flicker is to move step 4 of Handle Transition Frame to run after the Update the Rendering step. Something along the lines of marking the transition as "pending done", and scheduling a task to finalize the transition. Finalizing the transition would then confirm that the state is "pending done", and run the four steps of current step 4 of Handle Transition Frame

/cc @nt1m @emilio @noamr

**Comment by emilio** [comment]
Yeah Firefox's implementation also behaves the same and I think that solution is reasonable.

**Comment by noamr** [comment]
Works for me

**Comment by nt1m** [comment]
Seems ok to me, will let @mattwoodrow double check

**Comment by mattwoodrow** [comment]
Sounds fine to me too!

**Comment by astearns** [comment]
The CSSWG will automatically accept this resolution one week from now if no objections are raised here. Anyone can add an emoji to this comment to express support. If you do not support this resolution, please add a new comment.

Proposed Resolution: Change view transition finished promise timing to avoid flicker

**Comment by astearns** [comment]
RESOLVED: Change view transition finished promise timing to avoid flicker

**Comment by nt1m** [comment]
@noamr @vmpstr Could you help edit this into the spec? It would help move forward with implementation on my side.

**Comment by vmpstr** [comment]
A follow-up question here: there are two options of changing this timing, and I'm not sure which one is better

1.
   - update the rendering happens, which posts a task to complete
   - in a task, we run the finished promise while ::view-transition is still present
   - in the same task, we clean up ::view-transition and all transition related things

or

2.
   - update the rendering happens, which posts a task to complete
   - in a task, we clean up ::view-transition and all transition related things
   - in the same task, we run the finished promise without any transition related things

The latter is a bit hard to test reliably (or at least I haven't figured out a good way), since any kind of test becomes indistinguishable from us not posting any tasks to do the clean up which is the thing we want to avoid.

I'm leaning towards 1 because it allows the developer an opportunity to still look at the final state of the view transition objects in the finished promise (and it's easy to test :) )

@nt1m @emilio wdyt?

**Comment by noamr** [comment]
> A follow-up question here: there are two options of changing this timing, and I'm not sure which one is better
> 
> 1. * update the rendering happens, which posts a task to complete
>    * in a task, we run the finished promise while ::view-transition is still present
>    * in the same task, we clean up ::view-transition and all transition related things
> 
> or
> 
> 2. * update the rendering happens, which posts a task to complete
>    * in a task, we clean up ::view-transition and all transition related things
>    * in the same task, we run the finished promise without any transition related things
> 
> The latter is a bit hard to test reliably (or at least I haven't figured out a good way), since any kind of test becomes indistinguishable from us not posting any tasks to do the clean up which is the thing we want to avoid.
> 
> I'm leaning towards 1 because it allows the developer an opportunity to still look at the final state of the view transition objects in the finished promise (and it's easy to test :) )
> 
> [@nt1m](https://github.com/nt1m) [@emilio](https://github.com/emilio) wdyt?

It shouldn't matter because resolving promises always happens in the microtask queue.
So (2) would always be the result unless you do something funky like queue a microtask to clean up, or have the cleanup in yet another task after the `finished` promise.

**Comment by vmpstr** [comment]
Yeah, right, I guess I messed up the two options.

The clean up is always deferred to a separate task, but we can resolve the promise right during update the rendering (which will run the microtask checkpoint before the clean up task), or resolve the promise in the task (which will run after the cleanup in the microtask checkpoint)

**Comment by noamr** [comment]
> Yeah, right, I guess I messed up the two options.
> 
> The clean up is always deferred to a separate task, but we can resolve the promise right during update the rendering (which will run the microtask checkpoint before the clean up task),

Isn't that what happens today?

> Or resolve the promise in the task (which will run after the cleanup in the microtask checkpoint)

I think that is what the resolution says basically?

**Comment by vmpstr** [comment]
> Isn't that what happens today?

no, right now the clean up happens within update the rendering, which produces a visual frame without vt before finished promise runs. 



> I think that is what the resolution says basically?

Technically, but it's really about where the cleanup happens. If the cleanup is outside of the update the rendering then the finish resolution can still be within, since it will run at microtask checkpoint as the last thing in update the rendering loop. 

What I want to avoid is posting a separate task to do both cleanup and finish promise resolution, since that moves the promise callback to run at microtask checkpoint after the cleanup, vs at microtask checkpoint after update the rendering and before the task that runs the cleanup

**Comment by noamr** [comment]
> What I want to avoid is posting a separate task to do both cleanup and finish promise resolution, since that moves the promise callback to run at microtask checkpoint after the cleanup, vs at microtask checkpoint after update the rendering and before the task that runs the cleanup

We can schedule a higher priority task and check in that task that (a) cleanup wasn't done yet (b) the finished promise wasn't resolved yet.

**Comment by vmpstr** [comment]
> We can schedule a higher priority task and check in that task that (a) cleanup wasn't done yet (b) the finished promise wasn't resolved yet.

You mean for testing? I'm not sure how to do that from script. I tried with basically raf(setTimeout(..., 0)) but that seems to be unreliable. Do you have suggestions?

**Comment by nt1m** [comment]
Am I understanding this resolution correctly to change step 4 of handle transition frame to become this?

* If hasActiveAnimations is false:
  * If transition phase is "animating":
    * Set transition’s [phase](https://www.w3.org/TR/css-view-transitions-1/#viewtransition-phase) to "pending-done".
    * [Resolve](https://webidl.spec.whatwg.org/#resolve) transition’s [finished promise](https://www.w3.org/TR/css-view-transitions-1/#viewtransition-finished-promise).
    * (Do we return here? or do we let steps 5-6 run?) Return.
  * If transition phase is "pending-done":
    * [Clear view transition](https://www.w3.org/TR/css-view-transitions-1/#clear-view-transition) transition.
    * Set transition’s [phase](https://www.w3.org/TR/css-view-transitions-1/#viewtransition-phase) to "done".
    * Return.

**Comment by nt1m** [comment]
I guess the if pending-done bit would be in a task instead of handle transition frame IIUC

**Comment by vmpstr** [comment]
Yeah, I think roughly the resolution + discussion below it would end up with something like:

* If hasActiveAnimations is false:
    * If transition phase is "animating":
       * Set transition’s [phase](https://www.w3.org/TR/css-view-transitions-1/#viewtransition-phase) to "pending-done".
       * Post a task to continue the rest of the steps (and return after the task is posted)
       * if the transition phase is not 'pending-done' (transition skipped), abort the rest of the steps
       * clear the view transition state,
       * set the phase to done
       * resolve the finished promise

The difference from what you said is whether at the time finished promise callback runs, we should have already cleared the view transition state (it's finished), although visually last frame before that would still have displayed the view transition state

**Comment by nt1m** [comment]
I admit I don't have the bandwidth to think too precisely about this. I'll just trust whatever spec edits are being made here for implementation purposes.

cc @emilio in case he has any thoughts.

**Comment by nt1m** [comment]
@bramus @vmpstr Could we move the spec edits forward here? It would be helpful to get other browsers to adopt

**Comment by noamr** [comment]
> [@bramus](https://github.com/bramus) [@vmpstr](https://github.com/vmpstr) Could we move the spec edits forward here? It would be helpful to get other browsers to adopt

https://github.com/w3c/csswg-drafts/pull/12957
