### ISSUE TITLE
[css-scroll-anchoring] [css-scroll-snap] What's the optimal viewing rect on the root scroller?

### ISSUE THREAD

**Issue by emilio** [w3c/csswg-drafts#4393]
https://drafts.csswg.org/css-scroll-snap-1/#optimal-viewing-region

Firefox uses the visual viewport. Blink (if my read of their code is correct) uses the layout viewport (I think?).

The spec is unclear. It says "the scrollport".

See https://bugzilla.mozilla.org/show_bug.cgi?id=1585317#c4 for context.

If it should use the visual viewport, then scroll-padding should in theory resolve against that, rather than the layout viewport... right?

cc: @tabatkins @fantasai @bokand @skobes

**Comment by bokand** [comment]
+@majido 

IIRC Blink does use the layout viewport. I don't really see the use case for snapping to the visual viewport and using the layout viewport makes it more intuitive and simpler to reason about for web developers, IMHO.

**Comment by bokand** [comment]
Erm, never mind my comment above, snapping the visual viewport makes quite a bit of sense.

I think your understanding in Blink is correct and the behavior is a bit inconsistent; Blink uses the layout viewport as the optimal viewing region (at least, scroll-padding and the like is resolved against it) but it scrolls the visual viewport when snapping.

 > If it should use the visual viewport, then scroll-padding should in theory resolve against that, rather than the layout viewport... right?

I think that'd be more intuitive, yes, but that means that zooming in and out would have to invalidate style, right?

**Comment by emilio** [comment]
> I think that'd be more intuitive, yes, but that means that zooming in and out would have to invalidate style, right?

Percentages are not resolved during styling, only during layout... So it'd have to invalidate layout, I guess.

**Comment by theres-waldo** [comment]
Note, this came up for us in the context of scroll anchoring, which [also uses](https://drafts.csswg.org/css-scroll-anchoring/#anchor-node-selection) the "optimal viewing region".

We have scoll anchoring choose an anchor node in the visual viewport, because otherwise content in the visual viewport could actually shift even as we keep a node that's inside the layout viewport (but outside the visual viewport) anchored.

**Comment by tabatkins** [comment]
I wonder if we want to define the "scrollport" to be the visual viewport when talking about the root scroller, or if it should remain the layout viewport (which I think is what the current definition says) and we should define another term which does use the visual viewport?

**Comment by fantasai** [comment]
I'd agree that snapping should be resolved against the visual viewport: the whole point is to get the thing in view. However, I suspect scroll-padding should resolve against the layout viewport: a lot of its use cases are around avoiding certain fixed-positioned content, for example, and that resolves against the layout viewport if I'm understanding things correctly.

**Comment by fantasai** [comment]
Proposal is to clarify that snapping is to the visual viewport, but percentage values resolve against the layout viewport.

**Comment by nickburris** [comment]
Note that the [css-overflow spec seems clear that the scrollport is the visual viewport](https://www.w3.org/TR/css-overflow-3/#scrollport). I opened #4776 clarifying scroll-padding for the root scroller.

**Comment by fantasai** [comment]
Adjusted the edits to be a bit more precise, resulting in the following text:

> When applied to the root viewport, the offset is calculated and applied relative to the layout viewport (rather than the visual viewport) the same way as the corresponding inset properties on fixed-positioned boxes; the optimal viewing region is the remaining area that intersects with the visual viewport.

@emilio @bokand @theres-waldo @nickburris Does this seem clear and reasonable to you?

**Comment by theres-waldo** [comment]
That seems clear, thanks.

I think it's also a reasonable choice. The alternative I can think of would be to calculate the offset relative to the layout viewport but apply it relative to the visual viewport, which would have the (significant) downside that the optimal viewing region could be very small or even empty at high zoom levels.

**Comment by bokand** [comment]
+1 that looks good to me, thanks!
