### ISSUE TITLE
[cssom] broken links

### ISSUE THREAD

**Issue by svgeesus** [w3c/csswg-drafts#6463]
Found while preparing CSSOM-1 for publication:

error Lines: 1196, 1248, 1303 https://html.spec.whatwg.org/multipage/infrastructure.html
    Status: 200 OK

    Some of the links to this resource point to broken URI fragments (such as index.html#fragment). 
    Broken fragments:

        https://html.spec.whatwg.org/multipage/infrastructure.html#content-type (line 1196)
        https://html.spec.whatwg.org/multipage/infrastructure.html#document-base-url (lines 1248, 1303)

error Lines: 1286, 1337 https://html.spec.whatwg.org/multipage/semantics.html
    Status: 200 OK

    Some of the links to this resource point to broken URI fragments (such as index.html#fragment). 
    Broken fragments:

        https://html.spec.whatwg.org/multipage/semantics.html#style-sheet-ready (lines 1286, 1337)

error Lines: 1185, 1237, 1284, 4716 https://www.w3.org/TR/xml-stylesheet/
    Status: 200 OK

    Some of the links to this resource point to broken URI fragments (such as index.html#fragment). 
    Broken fragments:

        https://www.w3.org/TR/xml-stylesheet/#dt-xml-stylesheet-processing-instruction (lines 1185, 1237, 1284)

**Comment by svgeesus** [comment]
looks like base url should be https://html.spec.whatwg.org/multipage/urls-and-fetching.html#document-base-url

stylesheet pi should be https://www.w3.org/TR/xml-stylesheet/#the-xml-stylesheet-processing-instruction

**Comment by svgeesus** [comment]
@emilio broken links will block publication, #6446

**Comment by emilio** [comment]
@svgeesus I was looking into these, how do I see the remaining link errors? bikeshed doesn't seem to report these

**Comment by xfq** [comment]
I usually use the W3C Link Checker: https://validator.w3.org/checklink?uri=https%3A%2F%2Fdrafts.csswg.org%2Fcssom-1%2F&hide_type=all&depth=&check=Check

**Comment by emilio** [comment]
Thanks @xfq! I fixed the links (see issues above). @svgeesus mind confirming that there are not remaining broken links? Thank you.

**Comment by svgeesus** [comment]
I see three:

https://html.spec.whatwg.org/multipage/semantics.html#style-sheet-ready
https://html.spec.whatwg.org/multipage/infrastructure.html#content-type
https://www.w3c.org/TR/css-nesting-1/

The last one is easy, https://www.w3.org/TR/css-nesting-1/, which still doesn't work but will as soon as the FPWD is published.

**Comment by emilio** [comment]
> I see three:
> 
> https://html.spec.whatwg.org/multipage/semantics.html#style-sheet-ready

Oh, I missed one reference to that flag, on it.

> https://html.spec.whatwg.org/multipage/infrastructure.html#content-type

This one works for me?
 
> https://www.w3c.org/TR/css-nesting-1

And this one should be fine as per above. So I think https://github.com/w3c/csswg-drafts/pull/6539 should be the only thing left.
