### ISSUE TITLE
[css-shapes-2][css-borders-4] Add a way to change an element's shape

### ISSUE THREAD

**Issue by SebastianZ** [w3c/csswg-drafts#6997]
@LeaVerou mentioned an `element-shape` property in https://github.com/w3c/csswg-drafts/issues/6980#issuecomment-1020301916 as a way to influence the shape of an element. The idea behind that property is to change the shape of the element so that border, shadows, etc. follow that shape.

So far we have the `shape-outside` property which influences the float area. I suggest to extend this property to be able to specify that it not only affects the float area but also all the other boxes created for the element.

Sebastian

**Comment by jsnkuhn** [comment]
this issue about trying to get borders etc to play nice with clip-path seems related: #5881

**Comment by bradkemper** [comment]
I think we should either extend `shape-outside` or `clip-path` or both.

**Comment by bradkemper** [comment]
Also, add `clip-path` as a keyword value of shape-outside, so that shapes only have to be defined once, in the `clip-path` property, and used to also define the path of `shape-outside`.

**Comment by faceless2** [comment]
Big +1 to Brad's comments. We have `shape-outside` and `clip-path` already, they should be reused rather than adding another definition of the shape-of-a box. The `clip-path` value to shape-outside is also a good (and probably overdue) idea.

**Comment by jsnkuhn** [comment]
with the reuse of a `clip-path` like syntax in mind `clip-path` already has an `inset()` option right now that allows for a round option similar to border radius. So it seems like things are already primed to be extended for `corner-shape` 

```clip-path: inset(20px round 10px)```

does fell a bit strange hiding the corner-shape-ing just inside `inset()` though. 

wonder if something like `corners(angle round round 50%);` could be used to make the corners thing less of an after thought here.

**Comment by jsnkuhn** [comment]
would it theoretically in anyway be feasible to get `border-image` to follow an `element-shape` path? Like down the left side of this text box?

![border-image-shape](https://user-images.githubusercontent.com/1286791/176185694-e784301e-f3bd-4327-8f67-4ea275663e0e.png)

**Comment by SebastianZ** [comment]
Btw. just referencing #2180 in regard of the `clip-path` value for `shape-outside`.

Sebastian

**Comment by jsnkuhn** [comment]
I don't really think giving `clip-path` the ability to have borders/box-shadows etc is the right way to go here. `clip-path` is already doing what it's intended to do i.e clip a path. It makes more sense to for there to be a separate property to deal with the creation of an element shape.

There are plenty of existing use cases of having a rectangular shape that is revealed with a `clip-path` animation. No reason folks wouldn't want to do the same thing with non-rectangular shapes. If you are already using `clip-path` for the elements shape how would it be possible to reveal the element with a `clip-path` animation?

![GIF](https://user-images.githubusercontent.com/1286791/176573860-e781a074-6954-49e7-850e-d9c0cb834bbe.gif)

https://codepen.io/jsnkuhn/pen/BaryjEV?editors=1100

**Comment by jsnkuhn** [comment]
Ran across this page with lots of interestingly shaped elements: https://atlus.com/persona5/home.html

![image](https://user-images.githubusercontent.com/1286791/187215946-a2c47655-ed83-4981-aa74-c1d12406fb2b.png)

**Comment by smfr** [comment]
`shape-outside` is about wrapping content around an element. `clip-path` is about clipping, and does not affect border drawing.

I think the solution here is a property that allows the author to specify a shape that affects the painted border, like `border-shape` or `element-shape`. The author might want to specify a single path which is stroked to generate the border, or two paths which form the inner and outer edge of the painted border (i.e. a path with a hole), in which case the space between them is filled with the border color(s).

**Comment by noamr** [comment]
I think this is a duplicate of #5881 in some ways.

**Comment by smfr** [comment]
Here's a very rough proposal for a `border-shape` syntax, with the intent of having `border-shape` encompass `corner-shape` and the desire to have user-defined element shapes.

```
<corner-shape> = [round | bevel | scoop | notch]{1,4}
<border-line-style> = dotted | dashed | solid
<border-radius> = <length-percentage [0,∞]>{1,4} [ / <length-percentage [0,∞]>{1,4} ]?

border-shape: (<corner-shape> <border-radius>?)
              || (<basic-shape> <line-width> <border-line-style>? <geometry-box>?)
              || (<basic-shape> <geometry-box>? <basic-shape> <geometry-box>?)
```

If the `<corner-shape>` version is specified, this can be used to specify the corner treatment for each corner, and optionally border radii that override `border-radius` values. The appearance of corner shapes is influenced by border widths, as with border-radius currently (note this might be non-trivial for some corner shapes).

If the single `<basic-shape>` variant is specified, this provides a path, with the given stroke width, which is rendered instead of the border[1]. The path is resolved relative to the given `<geometry-box>`, defaulting to `border-box`. Colors are taken from the `border-color` property (different colors on each side are rendered with corner joins, as they are now with `border-radius`). The border is rendered by stroking the path, centered on the path (insetting an arbitrary path involves non-trivial compute, and masking to get an inset path doesn't work for paths with loops). Dotted and dashed paths are supported. (Double borders could also be supported by masking and rendering the path a second time for the center slot with clearing.) A future property could allow control over the dash origin.

If the double `<basic-shape>` variant is specified, the first shape is used as the outside of the border shape, and the second shape as the inside. The border fill is painted in the space between these two paths. Each path is resolved relative to the given `<geometry-box>`.

`border-clip: border-area` fill the border shape.

Box shadows follow the outer and inner border shapes as appropriate.

`border-shape` does not affect the box geometry, which is still computed using the widths specified via `border-width`. Areas of the shape that project outside the border-box are considered as ink overflow. Areas of the inner shape that project outside of the border-box will be considered part of the background area, so filled with backgrounds (we probably need a new value for `background-clip` to allow for this).

`border-shape` does not affect the flow of content inside the box.

The clipping of content behaves as it does for `border-radius`: the inside shape of the border clips content, if `overflow` is non-visible.

The shape variants of `border-shape` have no effect in cases where it's necessary to clip to the content box (replaced elements?). Currently border-radius does affect content box clipping in some cases, but it's not possible to easily inset arbitrary shapes to compute content shape clipping.

[1] _Maybe the rectangular border also renders, and the author has to set the color to `transparent` to hide it? The shape would then be a way to just extend the background._

Here's a screenshot for some in-progress experiments in WebKit:

![border-shape](https://github.com/user-attachments/assets/a94e73f8-1538-4730-9458-f7651857217d)
which is a rendering of
```
            padding: 40px;
            overflow: hidden;
            border: 60px solid transparent;
            box-shadow: 0 0 20px black, 0 0 20px black inset;
            border-shape:
                shape(from 0% 0%,
                    hline to 100%,
                    vline to 75%,
                    smooth by -8.295% 0% using -3.7% -2.2%,
                    smooth by -8.5% 12.8% using -4.1% 10.7%,
                    smooth by -7.9% -3.2% using -3.7% -5.2%,
                    smooth by -7.3% 9.3% using -2.7% 7.1%,
                    smooth by -9.0% 0% using -4.1% -2.3%,
                    smooth to 0.82% 100% using 0.82% 100%,
                    close) border-box,
                shape(from 10% 10%,
                    hline to 90%,
                    vline to 64.621%,
                    smooth by -8.295% 0% using -3.7% -2.2%,
                    smooth by -8.5% 12.8% using -4.1% 10.7%,
                    smooth by -7.9% -3.2% using -3.7% -5.2%,
                    smooth by -7.3% 9.3% using -2.7% 7.1%,
                    smooth by -9.0% 0% using -4.1% -2.3%,
                    smooth to 10% 90% using 10% 90%,
                    close) border-box;            
            background-image: linear-gradient(to bottom right, orange, blue, green), none;
            background-origin: border-box;
            background-clip: border-area, border-box;
```

**Comment by noamr** [comment]
> Here's a very rough proposal for a `border-shape` syntax, with the intent of having `border-shape` encompass `corner-shape` and the desire to have user-defined element shapes.
> 
> ```
> <corner-shape> = [round | bevel | scoop | notch]{1,4}
> <border-line-style> = dotted | dashed | solid
> <border-radius> = <length-percentage [0,∞]>{1,4} [ / <length-percentage [0,∞]>{1,4} ]?
> 
> border-shape: (<corner-shape> <border-radius>?)
>               || (<basic-shape> <line-width> <border-line-style>? <geometry-box>?)
>               || (<basic-shape> <geometry-box>? <basic-shape> <geometry-box>?)
> ```
> 
> If the `<corner-shape>` version is specified, this can be used to specify the corner treatment for each corner, and optionally border radii that override `border-radius` values. The appearance of corner shapes is influenced by border widths, as with border-radius currently (note this might be non-trivial for some corner shapes).
> 
> If the single `<basic-shape>` variant is specified, this provides a path, with the given stroke width, which is rendered instead of the border[1]. The path is resolved relative to the given `<geometry-box>`, defaulting to `border-box`. Colors are taken from the `border-color` property (different colors on each side are rendered with corner joins, as they are now with `border-radius`). The border is rendered by stroking the path, centered on the path (insetting an arbitrary path involves non-trivial compute, and masking to get an inset path doesn't work for paths with loops). Dotted and dashed paths are supported. (Double borders could also be supported by masking and rendering the path a second time for the center slot with clearing.) A future property could allow control over the dash origin.
> 
> If the double `<basic-shape>` variant is specified, the first shape is used as the outside of the border shape, and the second shape as the inside. The border fill is painted in the space between these two paths. Each path is resolved relative to the given `<geometry-box>`.
> 
> `border-clip: border-area` fill the border shape.
> 
> Box shadows follow the outer and inner border shapes as appropriate.
> 
> `border-shape` does not affect the box geometry, which is still computed using the widths specified via `border-width`. Areas of the shape that project outside the border-box are considered as ink overflow. Areas of the inner shape that project outside of the border-box will be considered part of the background area, so filled with backgrounds (we probably need a new value for `background-clip` to allow for this).
> 
> `border-shape` does not affect the flow of content inside the box.
> 
> The clipping of content behaves as it does for `border-radius`: the inside shape of the border clips content, if `overflow` is non-visible.
> 
> The shape variants of `border-shape` have no effect in cases where it's necessary to clip to the content box (replaced elements?). Currently border-radius does affect content box clipping in some cases, but it's not possible to easily inset arbitrary shapes to compute content shape clipping.
> 
> [1] _Maybe the rectangular border also renders, and the author has to set the color to `transparent` to hide it? The shape would then be a way to just extend the background._
> 
> Here's a screenshot for some in-progress experiments in WebKit:
> 
> ![border-shape](https://private-user-images.githubusercontent.com/20968/361641627-a94e73f8-1538-4730-9458-f7651857217d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQ3NTEyMjYsIm5iZiI6MTcyNDc1MDkyNiwicGF0aCI6Ii8yMDk2OC8zNjE2NDE2MjctYTk0ZTczZjgtMTUzOC00NzMwLTk0NTgtZjc2NTE4NTcyMTdkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MjclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODI3VDA5Mjg0NlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTA2ODdlZDUxNGRkMWQ1MDVjYTdmY2E2Zjk2MjQ5YWQ3NzUzODE3Mzk5MjFjZGZhNDVkMDc0MDlmYTRlY2YxZTgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.g4NeCvG1Fl2oEDxUXsDyHmtCG732t36Qp4Dfa9y2SPk) which is a rendering of
> 
> ```
>             padding: 40px;
>             overflow: hidden;
>             border: 60px solid transparent;
>             box-shadow: 0 0 20px black, 0 0 20px black inset;
>             border-shape:
>                 shape(from 0% 0%,
>                     hline to 100%,
>                     vline to 75%,
>                     smooth by -8.295% 0% using -3.7% -2.2%,
>                     smooth by -8.5% 12.8% using -4.1% 10.7%,
>                     smooth by -7.9% -3.2% using -3.7% -5.2%,
>                     smooth by -7.3% 9.3% using -2.7% 7.1%,
>                     smooth by -9.0% 0% using -4.1% -2.3%,
>                     smooth to 0.82% 100% using 0.82% 100%,
>                     close) border-box,
>                 shape(from 10% 10%,
>                     hline to 90%,
>                     vline to 64.621%,
>                     smooth by -8.295% 0% using -3.7% -2.2%,
>                     smooth by -8.5% 12.8% using -4.1% 10.7%,
>                     smooth by -7.9% -3.2% using -3.7% -5.2%,
>                     smooth by -7.3% 9.3% using -2.7% 7.1%,
>                     smooth by -9.0% 0% using -4.1% -2.3%,
>                     smooth to 10% 90% using 10% 90%,
>                     close) border-box;            
>             background-image: linear-gradient(to bottom right, orange, blue, green), none;
>             background-origin: border-box;
>             background-clip: border-area, border-box;
> ```

I'm sure other people would have more to say about the specifics, but my initial reaction is "let's do it!"

**Comment by smfr** [comment]
The single-shape syntax is a request to stroke the given path (which may contain multiple sub-paths). The two-stroke syntax is a request to fill the area between the paths. It's possible we should switch between these behaviors with a keyword, but then you might have an author providing a single-path path and requesting a fill, which would be an error (I don't think we ever want the border to act as a fill over the entire element).

**Comment by noamr** [comment]
> The single-shape syntax is a request to stroke the given path (which may contain multiple sub-paths). The two-stroke syntax is a request to fill the area between the paths. It's possible we should switch between these behaviors with a keyword, but then you might have an author providing a single-path path and requesting a fill, which would be an error (I don't think we ever want the border to act as a fill over the entire element).

Maybe I'm still getting this wrong, but is this equivalent to using a different winding-rule for fill and stroke? `evenodd` for fill and `nonzero` for stroke?

**Comment by yisibl** [comment]
@smfr For the example above, I'm curious, how would adding `border-bottom-right-radius` render?

**Comment by jsnkuhn** [comment]
Just for confirmation we are changing the entire shape of the element here correct?

If so shouldn't the property name be "element-shape" in seat of "border-shape"? The border is only that shape because it traces/strokes the element's shape. It also seems that a "border"/stroke would not be required and therefore calling it "border-shape" could be confusing. A border-less "border-shape" just seems odd to me. If you have a border-less `element-shape` the name still makes sense.

**Comment by jsnkuhn** [comment]
Agreed that "border-shape" would have the same semantics of `border-radius`. But the point is that those semantics are confusing. We've 15 years of precedent with blog posts titled something like "border-radius/rounded corners" because people did not know what `border-radius` was on it's own. This doesn't feel to me like something to lean into.

**Comment by smfr** [comment]
I feel like `border-shape` is more appropriate. It doesn't affect the box geometry (other than possibly adding ink overflow), so does not affect layout. It picks up the border colors, and `background-clip: border-area` fills the shape, so it is really best thought of as a customized border.

**Comment by jsnkuhn** [comment]
`border-radius` has a long standing issue with color "bleed" (for lack of a better term). When a parent and child element have the same `border-radius` the corners don't line up exactly and this potentially causes the parents background color to bleed through. Are these shaping properties all likely to have this same issue? If so is there anything that can done about this in the spec?

Firefox bug: https://bugzilla.mozilla.org/show_bug.cgi?id=664154
Chrome bug: https://issues.chromium.org/issues/41361515
Safari bug: https://bugs.webkit.org/show_bug.cgi?id=62639

**Comment by schenney-chromium** [comment]
I don't think there's anything that can be done at the spec level regarding bleeding around borders or backgrounds or between adjoining elements. I think it's already clear to almost everyone that things should not bleed and I can't think of a spec change that would make it easier to avoid bleeding.

The bugs are generally due to implementation of both the rendering engine and the underlying graphics systems. I'm beyond counting how many days of my life I have spent trying to fix color bleeding problems related to backgrounds and borders. At a meta level the problems are very hard to fix because a general solution requires globally knowledge of how everything should align, but what we have in practice is a logical tree.

**Comment by LeaVerou** [comment]
Let’s please not use `border-radius` as design precedent, it’s one of the recognized mistakes in the design of CSS: https://wiki.csswg.org/ideas/mistakes

**Comment by noamr** [comment]
> Let’s please not use `border-radius` as design precedent, it’s one of the recognized mistakes in the design of CSS: https://wiki.csswg.org/ideas/mistakes

The link said that we should have named it `corner-radius`. That makes sense because the radius itself applies to the corners and not to the whole border, but I don't see how it's a "mistake in design", or something that applies here? The path in this case does affect the whole border and not just the corners.

**Comment by LeaVerou** [comment]
> > Let’s please not use `border-radius` as design precedent, it’s one of the recognized mistakes in the design of CSS: [wiki.csswg.org/ideas/mistakes](https://wiki.csswg.org/ideas/mistakes)
> 
> The link said that we should have named it `corner-radius`. That makes sense because the radius itself applies to the corners and not to the whole border, but I don't see how it's a "mistake in design", or something that applies here? The path in this case does affect the whole border and not just the corners.

That is not the reason it's a mistake. It’s a mistake because it affects the element shape **whether there is a border or not**. Naming it `border-radius` was unduly influenced by its specification details (the fact that it rounds the border box) but as far as authors are concerned, that's almost an implementation detail.

**Comment by smfr** [comment]
I think you're suggesting that `element-shape` would be a better name, because even when a border is not present, the property would affect the shape of the background area, and how contents are clipped? That makes sense, but then the values of the property that are really about embellishing the border (e.g. the two-shape form) feel a bit odd as values for `element-shape`.

**Comment by schenney-chromium** [comment]
I would expect something like "element-shape" to affect layout, in the sense that other elements would somehow fit around the shape.  Here the element is still a rectangle, but it has a complex border around it that optionally draws and always clips the background.

The compromise between @LeaVerou and @smfr and myself may be "background-shape".

We also need to consider potential interactions with shadows, aka https://github.com/w3c/csswg-drafts/issues/7103, particularly when there are concave corners.

**Comment by SebastianZ** [comment]
It looks like we won't be able to have "one property to rule them all". Though @smfr's approach still seems like a great approach to handle the border shape issue.
And I agree with him that `border-shape` fits best here. As the background's shape can be adjusted to follow the border area via `background-clip: border-area`. And there is also a [`shape-inside` property defined in CSS Round Display 1](https://drafts.csswg.org/css-round-display/#shape-inside-property) (that spec. really needs a rebranding as it's about arbitrary display shapes), which affects the content area and also takes a `<basic-shape>`, and might possibly also take a `border-area` value.

With those three, authors can basically change the whole element's shape.

Regarding the suggested syntax for `border-shape`, I think it has a few mistakes in it based on how I understand @smfr's descriptions and it might also see some additions and relaxationst. Therefore, my interpretation of this is,

- the shape is meant to _either_ be defined via a `<corner-shape>`, the single- or the double-`<basic-shape>` syntax, but no combinations of those variants are allowed.
- the different variants are not meant to be surrounded by parentheses.
- corner shape syntax should follow what's defined in CSS Borders 4. (Currently, we only have `round` and `angle`, see https://github.com/w3c/csswg-drafts/issues/10747#issuecomment-2295384616) about the status of `scoop` and `notch` ‒ I'd be happy to add them back in.)
- the order of values is irrelevant and besides the shape definition itself, nothing is required.
- the line width may also be set for the double-`<basic-shape>` syntax, then only setting the width of the border box.

Given those points, I think the syntax of `border-shape` should look like this:

```ebnf
border-shape: [ <corner-shape> || <border-radius> ]
              | [ <basic-shape> [ <line-width> || <border-line-style> || <geometry-box> ] ]
              | [ <basic-shape> [ <line-width> || <geometry-box> ] ]{2}

<corner-shape> = [ round | angle ]{1,4}
<border-line-style> = dotted | dashed | solid
<border-radius> = <length-percentage [0,∞]>{1,4} [ / <length-percentage [0,∞]>{1,4} ]?
```

Open questions are:

- How does this interact with other properties like `corner-shape`, `border-radius`, `border-*-width`, `border-*-style`, etc.? Is it meant to be a shorthand for them?
- May [`<line-style>`](https://drafts.csswg.org/css-backgrounds-3/#typedef-line-style) be used instead of the restricted `<border-line-style>`?
- How are line styles meant to be drawn?
- Are the shapes restricted somehow to avoid overly huge ink overflows?

Sebastian

**Comment by smfr** [comment]
```
[ <basic-shape> [ <line-width> || <geometry-box> ] ]{2}
```
The two-shape form doesn't take a line width, because it just fills the space between the shapes. But I suppose you could stroke both shapes? If you allow that, then authors will want different colors and widths for the inner and outer strokes.

> How does this interact with other properties like corner-shape, border-radius, border-*-width, border-*-style, etc.? Is it meant to be a shorthand for them?

It could just subsume `corner-shape`. Do we need both?
Interaction with `border-radius` gets tricky because of all the longhands. Also specifying all corner radii in this property could get cumbersome. I'm not sure what to do here.

> May `<line-style>` be used instead of the restricted `<border-line-style>`?

These values don't make sense on arbitrary paths: `groove, ridge, inset, outset` and `double is hard to implement efficiently.

> How are line styles meant to be drawn?

That's why I limited to solid, dashed and dotted :)

> Are the shapes restricted somehow to avoid overly huge ink overflows?

I say no. Authors can already create large ink overflow with shadows.

**Comment by jsnkuhn** [comment]
An alternative to "corner-shape" I've brought up a couple of times is to include the the complete functionality of "corner-shape" in css-shapes as expanded options in inset(), xywh() and rect(). This currently includes `round` for corner rounding so seems like it could be expanded to include the other shapes and combinations of shapes from "corner-shape"?

```css
inset(0 round 12px);
inset(0 angle 8px);
inset(0 round none 12px );
inset(0 round angle notch scoop 12px / 24px ); 
```

**Comment by LeaVerou** [comment]
The ergonomics of the single shape version are very poor — essentially you are specifying a shape that is not shown anywhere in your layout, it’s neither the inner nor the outer shape.

I strongly believe we need to find a way to offset these paths so that the single shape syntax can be useful, since there is a **host** of use cases that only require a single shape (use cases with no borders for one). It cannot be an insurmountable problem to offset a closed path!

**Comment by smfr** [comment]
Offsetting paths with loops and holes (multiple subpaths) will give unexpected results (holes disappear).

**Comment by LeaVerou** [comment]
> Offsetting paths with loops and holes (multiple subpaths) will give unexpected results (holes disappear).

That’s fine since the vast majority of use cases won’t have loops and holes. We just need an algorithm that a) will work well for the cases we actually need here and b) will be well-defined for the rest (even if it produces poor results)

**Comment by fantasai** [comment]
@LeaVerou If we're offsetting by default (which I assume is your proposal) then we need to have reasonable behavior by default, though.

**Comment by LeaVerou** [comment]
So over the break @tabatkins and I came up with an algorithm for how to not only draw the border on a single shape, but even respect the different top, right, bottom, left border widths.

Conceptually, the general idea was: for each point along the path, you find the tangent, and draw a vector perpendicular to the tangent with a length calculated as follows:
- If the angle is a multiple of 90deg, then it directly maps to one of the four border widths.
- Otherwise, you compute its proximity to the two adjacent angles that are multiples of 90deg and do a weighed average of the two border widths.

I don’t have access to our sketches as I write this, but it seemed to us that this would produce a very nice result for many common cases, and a not-terrible result for edge cases.

Ideally, the single shape syntax should allow specifying either the border edge (and draw the border on the inside of it) or the padding edge (and draw the border on the outside of it). We'd still need to decide how to do line joins and miter limits.

@svgeesus @fserb we'd love your feedback!

**Comment by kizu** [comment]
Just quickly sharing two examples from [the latest Josh Comeau's blog redesign](https://www.joshwcomeau.com/blog/how-i-built-my-blog-v2/) which seem like a good use case for the `border-shape`:

<img width="140" alt="A screenshot of an “info” icon in the corner of a message box, with a thick border on the left going around it, as a single nicely rounded line." src="https://github.com/user-attachments/assets/d656d5b4-1fc7-43e3-a874-24e16cce88a0"> <img width="101" alt="A screenshot of a triangular warning icon, again, with a line going around it, following the triangular shape at a distance." src="https://github.com/user-attachments/assets/4e27d083-f425-4e66-a809-6b8aaa7f8a89">

**Comment by smfr** [comment]
The current proposal doesn't have a way to just get that border on the left edge (with rounded ends), though.

**Comment by tabatkins** [comment]
> So over the break @tabatkins and I came up with an algorithm for how to not only draw the border on a single shape, but even respect the different top, right, bottom, left border widths.

A little more detail on our motivation:

It's reasonable to view border-shape as providing three levels of increasing complexity & power for specifying borders: the border-* properties define a rounded rect path that gets stroked; the single-path version defines an *arbitrary* path that gets stroked; the two-path version defines an *Iarbitrary shape* that gets filled. Generally, we want increasing complexity to track with increased power, so authors that want only a small deviation from the built-in stuff can just go up a small amount in complexity, rather than having to jump all the way to some "primitive" version that's super hard to work with (but super powerful).

So, the "rounded-rect" borders can have up to four distinct widths and colors, one for each horizontal/vertical side, with the rounded corners smoothly interpolating between the values. Our proposal is, we think, both the simplest and most natural way to reproduce this ability in the single-path syntax, with the path direction dictating which of the four border-width/color values to draw from (or which two to interpolate between, and by how much).

If you use the single-path to produce a rounded rect, or any reasonably close variation on that, you'll get a result essentially identical to what is defined for the border-* properties today. (The way the corners are interpolated will be slightly different, which I think is unavoidable - I don't think the corner interpolation rules can be applied to an arbitrary path without an explosion of complexity. But I could be wrong about that.)

If you do *other* shapes, you'll still get a *reasonable* result, with decent control knobs to twiddle. If this *still* isn't enough, the two-path syntax still exists, but we think this should provide enough power to the single-path syntax that you'll often be satisfied.

-------------

We could also provide a further intermediate syntax, where you can provide the colors and widths along the path *explicitly*, tied to the path distance; similar to defining gradient stops. We're already using that syntax in gradients and in linear(), and will likely use it in more places (cubic splines for more easing?), so it is a familiar pattern to work with. This is more complex than needed for simple shapes, but is still vastly less complicated than the two-path syntax.

**Comment by tabatkins** [comment]
Here's my fuller proposal, in more detail:

* By default, the single-path syntax determines its stroke width and color by consulting the border-width and border-color properties. Its width and color at any point depends on the path direction: directly to the right takes from `border-top-*`, directly down takes from `border-left-*`, etc; between those angles it linearly interpolates the width and color.
* Possibly, you can override this by specifying a single specific width and color in the syntax.
* Optionally, you can provide a gradient-stop-like list of widths and colors, each associated with a path distance (0% indicating the start, and 100% indicating the end, or lengths can be used). This overrides width/color behavior from the border-* properties. Possibly we just let this completely handle the previous bullet's case, since you can just write a single stop and get that behavior.

**Comment by noamr** [comment]
1. Wouldn't we want the same inner/outer functionality for the border-radius/corner-radius case? Like have rounded corners of different radiuses outside and inside? Feels a bit arbitrary that this simple version is only a one-shape syntax and the full basic-shape syntax doesn't include it. Perhaps we could utilize `outline` for this, where the inner shape strokes based on outline values and the outer shape strokes based on border values? In any case the rectangular outline makes little sense here. 

2. It's very surprising for me that `background` is what fills between the shapes. I would expect backgrounds to fill the inside shape, like in `border-radius`. I think we should find some semantic that works with `border-image` and aligns with Tab's proposal above for how the different border-widths work.

**Comment by smfr** [comment]
I understand the motivation for the single path syntax taking its widths from `border-width`, but I think in practice this is going to be pretty hard to implement. The proposal to inset the path by taking a perpendicular line at each point whose length is an interpolated width is interesting, but may result in a generated path with thousands of points; both the computation and rendering could be slow. Perhaps there's a way to do something similar with a scale transform which just scales the path, using a center point that takes the border widths into account?

> Optionally, you can provide a gradient-stop-like list of widths and colors, each associated with a path distance (0% indicating the start, and 100% indicating the end, or lengths can be used)

I don't think this will work very well if you apply it to boxes with different aspect ratios; the author would have a hard time matching gradient points with the box corners.

> It's very surprising for me that background is what fills between the shapes

I'm not sure it does? I think we can fill the space between the inner and outer shapes with border colors by default, with the usual diagonal corner joins.

**Comment by noamr** [comment]
> > It's very surprising for me that background is what fills between the shapes
> 
> I'm not sure it does? I think we can fill the space between the inner and outer shapes with border colors by default, with the usual diagonal corner joins.

I guess that's what I understood from https://github.com/w3c/csswg-drafts/issues/6997#issuecomment-2311513957?

**Comment by tabatkins** [comment]
Or, another alternative: define *another* function, `stroke()`, which is identical to `shape()` but specifically defines a stroked path. It can then have the additional grammar items that handle stroke width and color, along with future items in a prelude argument like stroke direction (center/left/right) and such. (And it would *not* have the fill-specific items in its prelude argument, like the nonzero/evenodd keyword that `shape()` has.)

Then, individual contexts would define whether they expect a `<shape>` or a `<stroke>`. If you pass `stroke()` to a `<shape>`, it's allowed, but we ignore all the stroke-specific stuff and default the fill-specific details in a context-specific manner. If you pass `shape()` (or any of the basic-shape function) to a `<stroke>`, it's allowed, but we ignore all the fill-specific stuff and default the stroke-specific details in a context-specific manner (such as getting the stroke width from 'border-top-width' or something). (We already do this if you use `path()` or `shape()` in Motion Path, for instance; the `nonzero`/`evenodd` keyword is simply ignored, since it actually takes a *third* semantic type, a plain ol' path.)

So the one-path syntax would actually be a `<stroke>`; the two-path syntax would be a pair of `<basic-shape>`s.

**Comment by smfr** [comment]
> What's determining the angle/position of the color change there? It can't just be radial lines from the center, as that would mean the three sharp corners would only look right if the border-width ratios happened to match the box's own aspect ratio.

Exactly the same as the color joins with border-radius and different border widths; I think the joins are the connecting lines between the corners of the border box and the padding box.

**Comment by tabatkins** [comment]
I'm still not sure how that works - the four corners can all have completely different angles, and lines extended from them aren't guaranteed to meet in a single point (in fact, they usually won't). Do you, like, find their first intersection points, then connect *those* points with a line, to divvy up the interior into four zones (some of which might be trapezoidal), and then fill the border shape accordingly?

**Comment by noamr** [comment]
> I'm still not sure how that works - the four corners can all have completely different angles, and lines extended from them aren't guaranteed to meet in a single point (in fact, they usually won't). Do you, like, find their first intersection points, then connect _those_ points with a line, to divvy up the interior into four zones (some of which might be trapezoidal), and then fill the border shape accordingly?

That's what seems the most simple and logical to me to do with varying `border-color` and `border-width`. It's a lot simpler than trying to follow the perpendiculars, and would produce a much more coherent result when you have different color+width pairs. Perhaps we should start with that and check if we can allow more complex control later on?

**Comment by noamr** [comment]
Some thought about how `border-shape` works with `border-width`  (hopefully we'll have time to discuss it at the F2F):
It would be confusing in some scenarios if `border-width` affected both the box model and the stroke of a shape that might not be boxy at all. An author might change the `border-width` in order to change the stroke, to find out that it moves the child elements because the padding box had now moved...

This is an issue with `border-shape` being purely decorative on one hand, but respecting layout properties for its style on the other hand.

I wonder if `border-shape` should have a `stroke` in addition to the shape(s), which could have the `border-width` as a default. Same for `fill` and `border-color`.

**Comment by fserb** [comment]
One proposal for `border-width` interaction. Writing 

Break it down in two steps.

Step 1. Assume a `width(t)` function that returns the width of the border parametrized over its length (`t=0` begin of the path,, `t=1` end of a continuous path). For each path, the `width(t)` function can be applied to create an outer shape by moving the path outside in the direction of the normal of the path.

Step 2. How to build `width(t)`. One option is to allow the user to specify a function or 1d gradient directly for each continuous path. But let's ignore that for now. Can we build a reasonable function given `border-width`? I think so. We can define "control points" (similar to what we have today): `0 - 0.25 - 0.5 - 0.75 - 1.0`. Each interval gets one width. And then we specify a transition range: so, something like: `width(t) = border-top-width [0.05, 0.2], lerp(top, right) [0.2, 0.3], right [0.3, 0.45] ... etc`. We can decide how much control/flexibility to give. This function would be applied to every continuous path on the shape.

Would something like this work?

**Comment by noamr** [comment]
> One proposal for `border-width` interaction.
> 
> Break it down in two steps.
> 
> Step 1. Assume a `width(t)` function that returns the width of the border parametrized over its length (`t=0` begin of the path,, `t=1` end of a continuous path). For each path, the `width(t)` function can be applied to create an outer shape by moving the path outside in the direction of the normal of the path.
> 
> Step 2. How to build `width(t)`. One option is to allow the user to specify a function or 1d gradient directly for each continuous path. But let's ignore that for now. Can we build a reasonable function given `border-width`? I think so. We can define "control points" (similar to what we have today): `0 - 0.25 - 0.5 - 0.75 - 1.0`. Each interval gets one width. And then we specify a transition range: so, something like: `width(t) = border-top-width [0.05, 0.2], lerp(top, right) [0.2, 0.3], right [0.3, 0.45] ... etc`. We can decide how much control/flexibility to give. This function would be applied to every continuous path on the shape.
> 
> Would something like this work?

I'm going to open separate issues for this once the draft is in. Let's add these ideas there
